export const appBridge = {
  setScreen: () => {},
  setErrorMessage: () => {},
  setAdsRemoved: () => {},
  setInterstitialReady: () => {},
  setPendingInterstitial: () => {},
  setShouldShowInterstitial: () => {},
  showToast: () => {},
  setAppSettings: () => {},
  setCrownWallet: () => {},
  appSettings: null,
  anonymousUserId: '',
  crownWallet: null,
  adsRemoved: false,
  interstitialReady: false,
  pendingInterstitial: false,
  interstitialRef: { current: null },
  rewardedRef: { current: null },
  toastMessage: '',
};
