import {
  getOrCreateUser,
  getWallet,
  insertLedger,
  restFetch,
  readJson,
  saveWallet,
  spendOneCrown,
  totalCrowns,
} from '../_shared/db.ts';
import { handleOptions, jsonResponse, textResponse } from '../_shared/http.ts';

const locations = ['home', 'market', 'estate', 'ballroom', 'garden', 'library', 'royal', 'kitchen', 'park', 'carriage'];
const effectTypes = ['romance', 'ambition', 'family', 'risk', 'retreat', 'deception', 'kindness', 'defiance', 'reputation', 'court'];

const pickLocation = (gameState: Record<string, unknown>, choice: Record<string, unknown> | null, isNewGame: boolean) => {
  const requested = String(choice?.nextLocationId || gameState.lastSettingId || '');
  if (locations.includes(requested)) return requested;
  return isNewGame ? 'home' : 'market';
};

const fallbackScene = (
  gameState: Record<string, unknown>,
  choice: Record<string, unknown> | null,
  isNewGame: boolean,
) => {
  const playerName = String(gameState.playerName || 'Eleanor');
  const locationId = pickLocation(gameState, choice, isNewGame);
  const target = Array.isArray(gameState.currentSceneCharacters) && gameState.currentSceneCharacters[0]
    ? String(gameState.currentSceneCharacters[0])
    : null;

  return {
    sceneText: isNewGame
      ? `Your first morning as ${playerName} begins with a letter tucked beneath the breakfast plate, its seal pressed too hard into the wax. The house is quiet, but the message inside promises that society has already begun to move around you.`
      : `The consequence of your choice follows you into the next room like a whispered announcement. Someone has noticed, someone has judged, and somewhere nearby a new opportunity waits behind good manners and a carefully lowered voice.`,
    locationId,
    charactersPresent: target ? [target] : [],
    temporaryExtras: isNewGame ? ['Mrs. Vale'] : ['Miss Hartley'],
    promoteTemporaryCharacter: false,
    hiddenStatDeltas: {
      scandal: 0,
      ambition: isNewGame ? 1 : 0,
      security: 0,
      familyDuty: 0,
      reputation: 1,
      courtFavour: 0,
    },
    choices: [
      {
        text: 'Answer with careful grace',
        effectType: 'reputation',
        targetCharacter: target,
        relationshipDelta: target ? 1 : 0,
        riskDelta: 0,
        nextLocationId: locationId,
        endingCandidate: null,
      },
      {
        text: 'Press for the truth',
        effectType: 'ambition',
        targetCharacter: target,
        relationshipDelta: 0,
        riskDelta: 1,
        nextLocationId: 'library',
        endingCandidate: null,
      },
      {
        text: 'Withdraw before gossip gathers',
        effectType: 'retreat',
        targetCharacter: null,
        relationshipDelta: 0,
        riskDelta: 0,
        nextLocationId: 'home',
        endingCandidate: null,
      },
    ],
    memoryUpdate: isNewGame
      ? `${playerName} began a new story with society already watching.`
      : `${playerName} continued after choosing ${choice?.text || 'an uncertain path'}.`,
    continuityCheck: 'Demo-safe Supabase fallback scene generated by the Edge Function.',
  };
};

const normalizeScene = (
  scene: Record<string, unknown>,
  expectedLocationId: string,
) => ({
  sceneText: String(scene.sceneText || ''),
  locationId: locations.includes(String(scene.locationId)) ? String(scene.locationId) : expectedLocationId,
  charactersPresent: Array.isArray(scene.charactersPresent) ? scene.charactersPresent.map(String).slice(0, 5) : [],
  temporaryExtras: Array.isArray(scene.temporaryExtras) ? scene.temporaryExtras.map(String).slice(0, 5) : [],
  promoteTemporaryCharacter: Boolean(scene.promoteTemporaryCharacter),
  hiddenStatDeltas: typeof scene.hiddenStatDeltas === 'object' && scene.hiddenStatDeltas ? scene.hiddenStatDeltas : {},
  choices: Array.isArray(scene.choices)
    ? scene.choices.slice(0, 5).map((choice) => {
      const item = choice && typeof choice === 'object' ? choice as Record<string, unknown> : {};
      return {
        text: String(item.text || 'Continue'),
        effectType: effectTypes.includes(String(item.effectType)) ? String(item.effectType) : 'reputation',
        targetCharacter: item.targetCharacter ? String(item.targetCharacter) : null,
        relationshipDelta: Number(item.relationshipDelta || 0),
        riskDelta: Number(item.riskDelta || 0),
        nextLocationId: locations.includes(String(item.nextLocationId)) ? String(item.nextLocationId) : expectedLocationId,
        endingCandidate: item.endingCandidate ? String(item.endingCandidate) : null,
      };
    })
    : [],
  memoryUpdate: String(scene.memoryUpdate || ''),
  continuityCheck: String(scene.continuityCheck || ''),
});

const isValidScene = (scene: ReturnType<typeof normalizeScene>) =>
  scene.sceneText.trim().length >= 160 &&
  locations.includes(scene.locationId) &&
  scene.choices.length >= 3 &&
  scene.choices.every((choice) => choice.text.trim().length >= 4 && effectTypes.includes(choice.effectType));

const callOpenAi = async (
  requestBody: Record<string, unknown>,
  expectedLocationId: string,
) => {
  const apiKey = Deno.env.get('OPENAI_API_KEY');
  if (!apiKey) return null;

  const model = Deno.env.get('OPENAI_MODEL') || 'gpt-4o-mini';
  const response = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model,
      temperature: 0.8,
      response_format: { type: 'json_object' },
      messages: [
        {
          role: 'system',
          content:
            'You write concise interactive Regency fiction. Return only valid JSON matching this shape: sceneText, locationId, charactersPresent, temporaryExtras, promoteTemporaryCharacter, hiddenStatDeltas, choices, memoryUpdate, continuityCheck. Use 3 to 5 choices. Valid locations are home, market, estate, ballroom, garden, library, royal, kitchen, park, carriage. Valid effectType values are romance, ambition, family, risk, retreat, deception, kindness, defiance, reputation, court.',
        },
        {
          role: 'user',
          content: JSON.stringify({
            expectedLocationId,
            request: requestBody,
          }),
        },
      ],
    }),
  });

  const payload = await response.json();
  if (!response.ok) {
    throw new Error(payload?.error?.message || `OpenAI request failed with status ${response.status}`);
  }
  const content = payload?.choices?.[0]?.message?.content || '';
  return JSON.parse(content);
};

const saveStoryState = async (
  userId: string,
  requestBody: Record<string, unknown>,
  scene: Record<string, unknown>,
) => {
  const gameState = requestBody.gameState && typeof requestBody.gameState === 'object'
    ? requestBody.gameState as Record<string, unknown>
    : {};
  const response = await restFetch('story_states?on_conflict=user_id', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Prefer: 'resolution=merge-duplicates',
    },
    body: JSON.stringify([{
      user_id: userId,
      turn_count: Number(gameState.turnCount || 0) + 1,
      current_location_id: scene.locationId || 'home',
      current_phase: requestBody.isNewGame ? 'opening' : 'rising_action',
      memory_summary: String(scene.memoryUpdate || gameState.memorySummary || ''),
      adjacent_location_history_json: gameState.adjacentLocationHistory || [],
      recent_extras_json: gameState.recentExtras || {},
      major_characters_json: gameState.majorCharacters || {},
      relationships_json: gameState.relationships || {},
      hidden_stats_json: gameState.hiddenStats || {},
      ending_risk_json: gameState.endingRisk || {},
      last_scene_json: scene,
    }]),
  });
  await readJson(response);
};

const saveTurn = async (
  userId: string,
  requestBody: Record<string, unknown>,
  scene: Record<string, unknown>,
  status: string,
  crownCharged: boolean,
) => {
  const response = await restFetch('ai_turns', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify([{
      user_id: userId,
      model: Deno.env.get('OPENAI_MODEL') || 'gpt-4o-mini',
      request_json: requestBody,
      response_json: scene,
      status,
      crown_charged: crownCharged,
    }]),
  });
  await readJson(response);
};

Deno.serve(async (request) => {
  const optionsResponse = handleOptions(request);
  if (optionsResponse) return optionsResponse;

  let requestBody: Record<string, unknown> = {};
  try {
    requestBody = await request.json();
    const anonymousUserId = String(requestBody.anonymousUserId || '').trim();
    if (!anonymousUserId) return textResponse('anonymousUserId is required.', 400);

    const user = await getOrCreateUser(anonymousUserId);
    const wallet = await getWallet(user.id);
    const spent = spendOneCrown(wallet);
    if (!spent.spent) {
      return jsonResponse({ code: 'NO_CROWNS', error: 'No Crowns available.', wallet }, 402);
    }

    const gameState = requestBody.gameState && typeof requestBody.gameState === 'object'
      ? requestBody.gameState as Record<string, unknown>
      : {};
    const choice = requestBody.choice && typeof requestBody.choice === 'object'
      ? requestBody.choice as Record<string, unknown>
      : null;
    const expectedLocationId = pickLocation(gameState, choice, Boolean(requestBody.isNewGame));

    let rawScene = await callOpenAi(requestBody, expectedLocationId);
    const usedOpenAi = Boolean(rawScene);
    if (!rawScene) rawScene = fallbackScene(gameState, choice, Boolean(requestBody.isNewGame));
    const scene = normalizeScene(rawScene, expectedLocationId);
    if (!isValidScene(scene)) {
      await saveTurn(user.id, requestBody, scene, 'invalid', false);
      return textResponse('Story generation returned an invalid scene.', 502);
    }

    const savedWallet = await saveWallet(user.id, spent.wallet);
    await insertLedger(user.id, -1, 'ai_turn', 'AI story turn generated.');
    await saveStoryState(user.id, requestBody, scene);
    await saveTurn(user.id, requestBody, scene, 'valid', true);

    return jsonResponse({
      scene,
      wallet: savedWallet,
      crownsRemaining: totalCrowns(savedWallet),
      source: usedOpenAi ? 'backend' : 'backend_fallback',
    });
  } catch (error) {
    return textResponse(error instanceof Error ? error.message : String(error), 500);
  }
});
