import { StyleSheet } from 'react-native';
import { colors } from '../constants/colors';

export const appStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: colors.accent,
    backgroundColor: colors.header,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  title: {
    fontSize: 26,
    fontFamily: 'serif',
    color: colors.title,
  },
  subtitle: {
    fontSize: 12,
    color: colors.muted,
  },
  relationshipDisplay: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.accent,
    backgroundColor: colors.overlay,
  },
  relationshipText: {
    color: colors.text,
    fontSize: 12,
  },
  menuButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    backgroundColor: colors.button,
    borderWidth: 1,
    borderColor: colors.accent,
  },
  menuButtonText: {
    color: colors.text,
    fontSize: 12,
  },
  burgerButton: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.accent,
    backgroundColor: colors.button,
    alignItems: 'center',
  },
  burgerIcon: {
    width: 22,
    marginBottom: 4,
  },
  burgerLine: {
    height: 2,
    backgroundColor: colors.text,
    marginBottom: 3,
    borderRadius: 2,
  },
  burgerText: {
    color: colors.text,
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  crownHeaderPill: {
    paddingVertical: 7,
    paddingHorizontal: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.title,
    backgroundColor: 'rgba(212, 175, 55, 0.16)',
  },
  crownHeaderText: {
    color: colors.title,
    fontSize: 14,
    fontFamily: 'serif',
  },
  chatArea: {
    flex: 1,
    paddingHorizontal: 10,
    paddingVertical: 12,
  },
  openBookFrame: {
    flex: 1,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: 'rgba(212, 175, 55, 0.48)',
    backgroundColor: '#4a2a16',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.34,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  openBookBackdrop: {
    ...StyleSheet.absoluteFillObject,
    flexDirection: 'row',
    backgroundColor: '#5a321a',
  },
  openBookPageLeft: {
    flex: 1,
    marginVertical: 10,
    marginLeft: -300,
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
    backgroundColor: '#ead9b7',
    borderRightWidth: 1,
    borderRightColor: 'rgba(89, 53, 24, 0.2)',
  },
  openBookSpine: {
    width: 16,
    marginVertical: 10,
    backgroundColor: 'rgba(92, 54, 24, 0.32)',
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: 'rgba(70, 38, 18, 0.24)',
  },
  openBookPageRight: {
    flex: 1,
    marginVertical: 10,
    marginRight: 10,
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
    backgroundColor: '#f1e3c5',
    borderLeftWidth: 1,
    borderLeftColor: 'rgba(89, 53, 24, 0.12)',
  },
  bookScroll: {
    flex: 1,
  },
  errorBanner: {
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 4,
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.accent,
    backgroundColor: colors.overlay,
  },
  errorText: {
    color: colors.text,
    fontSize: 13,
    lineHeight: 18,
  },
  chatContent: {
    paddingVertical: 12,
    paddingHorizontal: 22,
    paddingBottom: 2,
  },
  choicesArea: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: colors.footer,
    borderTopWidth: 1,
    borderTopColor: colors.accent,
  },
  choicesAreaMinimized: {
    paddingVertical: 8,
  },
  panelsRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 6,
    gap: 8,
  },
  relationshipPanel: {
    backgroundColor: colors.panel,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.accent,
    paddingVertical: 4,
    paddingHorizontal: 8,
    width: 190,
  },
  relationshipLabel: {
    color: colors.muted,
    fontSize: 10,
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  relationshipValue: {
    color: colors.text,
    fontSize: 13,
    fontFamily: 'serif',
  },
  locationPanel: {
    backgroundColor: colors.panel,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.accent,
    paddingVertical: 5,
    paddingHorizontal: 8,
    flex: 1,
    minWidth: 120,
  },
  locationLabel: {
    color: colors.muted,
    fontSize: 11,
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  locationValue: {
    color: colors.text,
    fontSize: 14,
    fontFamily: 'serif',
  },
  choiceHint: {
    color: '#6d4122',
    fontSize: 13,
    textAlign: 'center',
    paddingVertical: 12,
    fontFamily: 'serif',
  },
  choiceHintRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingVertical: 8,
  },
  skipButton: {
    borderWidth: 1,
    borderColor: '#6d4122',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
  },
  skipButtonText: {
    color: '#6d4122',
    fontSize: 12,
    fontFamily: 'serif',
    letterSpacing: 0.4,
  },
  expandChoicesButton: {
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: colors.title,
    borderRadius: 16,
    paddingVertical: 8,
    paddingHorizontal: 18,
    backgroundColor: 'rgba(212, 175, 55, 0.16)',
  },
  expandChoicesButtonText: {
    color: colors.title,
    fontSize: 13,
    fontFamily: 'serif',
    letterSpacing: 0.4,
  },
  choiceScroll: {
    maxHeight: 210,
  },
  choiceScrollContent: {
    paddingBottom: 4,
  },
  choiceActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  choiceActionButton: {
    flex: 1,
    marginHorizontal: 4,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.accent,
    backgroundColor: colors.button,
  },
  choiceActionText: {
    color: colors.text,
    fontSize: 12,
  },
  choiceButton: {
    borderWidth: 1,
    borderColor: colors.accent,
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 6,
    backgroundColor: colors.choice,
    marginBottom: 8,
  },
  choiceManuscript: {
  },
  choiceInlineButton: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    borderWidth: 1,
    borderColor: 'rgba(109, 65, 34, 0.42)',
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(255, 249, 232, 0.84)',
    marginBottom: 10,
  },
  choiceNumber: {
    minWidth: 24,
    height: 24,
    borderRadius: 12,
    overflow: 'hidden',
    textAlign: 'center',
    lineHeight: 24,
    color: '#ead9b7',
    backgroundColor: '#6d4122',
    fontFamily: 'serif',
    fontSize: 13,
  },
  choiceFooterHint: {
    color: colors.muted,
    fontSize: 12,
    textAlign: 'center',
    fontFamily: 'serif',
  },
  choiceText: {
    color: '#4b2c17',
    fontSize: 15,
    lineHeight: 21,
    fontFamily: 'serif',
    flex: 1,
  },
  choiceDisabled: {
    opacity: 0.5,
  },
  buttonDisabled: {
    opacity: 0.4,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(17, 8, 4, 0.78)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
  },
  modalContent: {
    backgroundColor: '#ead9b7',
    padding: 24,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: 'rgba(109, 65, 34, 0.64)',
    width: '85%',
    shadowColor: '#000',
    shadowOpacity: 0.42,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 10,
  },
  relationshipModalContent: {
    backgroundColor: '#ead9b7',
    paddingVertical: 18,
    paddingHorizontal: 18,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: 'rgba(109, 65, 34, 0.64)',
    width: '84%',
    maxWidth: 380,
  },
  relationshipModalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
  },
  relationshipModalName: {
    color: '#4b2c17',
    fontSize: 14,
    flex: 1,
    marginRight: 12,
    fontFamily: 'serif',
  },
  relationshipModalScore: {
    color: '#6d4122',
    fontSize: 13,
    textTransform: 'capitalize',
  },
  modalTitle: {
    color: '#6d4122',
    fontSize: 21,
    marginBottom: 12,
    textAlign: 'center',
    fontFamily: 'serif',
  },
  modalBody: {
    color: '#4b2c17',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 16,
    textAlign: 'center',
  },
  modalButton: {
    paddingVertical: 11,
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#6d4122',
    backgroundColor: '#6d4122',
    marginTop: 8,
  },
  modalButtonText: {
    color: '#f4e7c8',
    textAlign: 'center',
    fontFamily: 'serif',
  },
  drawerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    alignItems: 'flex-end',
  },
  drawerContent: {
    width: '72%',
    height: '100%',
    backgroundColor: colors.panel,
    paddingTop: 36,
    paddingHorizontal: 20,
    borderLeftWidth: 1,
    borderLeftColor: colors.accent,
  },
  drawerTitle: {
    color: colors.title,
    fontSize: 18,
    marginBottom: 16,
  },
  drawerButton: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.accent,
    backgroundColor: colors.button,
    marginBottom: 10,
  },
  drawerButtonText: {
    color: colors.text,
    fontSize: 13,
  },
  drawerButtonDisabled: {
    opacity: 0.5,
  },
  settingsHeader: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.accent,
    backgroundColor: colors.header,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  settingsTitle: {
    color: colors.title,
    fontSize: 20,
  },
  settingsList: {
    padding: 20,
    flex: 1,
  },
  settingsListContent: {
    paddingBottom: 36,
  },
  settingRowStacked: {
    backgroundColor: colors.panel,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.accent,
    padding: 16,
    marginBottom: 12,
  },
  settingRowHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  shopScrollContent: {
    padding: 20,
    paddingBottom: 36,
  },
  settingRow: {
    backgroundColor: colors.panel,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.accent,
    padding: 16,
    marginBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  settingLabel: {
    color: colors.text,
    fontSize: 15,
  },
  settingValue: {
    color: colors.muted,
    fontSize: 13,
  },
  settingButton: {
    backgroundColor: colors.panel,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.accent,
    padding: 16,
    alignItems: 'center',
    marginTop: 4,
  },
  settingButtonText: {
    color: colors.text,
    fontSize: 15,
  },
  settingDescription: {
    color: colors.muted,
    fontSize: 14,
    marginBottom: 12,
    textAlign: 'center',
  },
  settingDescriptionText: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 8,
  },
  toggleButton: {
    borderWidth: 1,
    borderColor: colors.accent,
    borderRadius: 14,
    paddingVertical: 7,
    paddingHorizontal: 14,
    backgroundColor: colors.button,
    minWidth: 58,
    alignItems: 'center',
  },
  toggleButtonActive: {
    backgroundColor: 'rgba(230, 201, 106, 0.18)',
    borderColor: colors.title,
  },
  toggleButtonText: {
    color: colors.text,
    fontSize: 13,
  },
  stepperRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 12,
  },
  stepperButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.accent,
    backgroundColor: colors.button,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperButtonText: {
    color: colors.text,
    fontSize: 20,
  },
  textSizeBar: {
    flex: 1,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.overlay,
    overflow: 'hidden',
  },
  textSizeBarFill: {
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.title,
  },
  optionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  optionPill: {
    borderWidth: 1,
    borderColor: colors.accent,
    borderRadius: 14,
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: colors.button,
  },
  optionPillActive: {
    backgroundColor: colors.title,
    borderColor: colors.title,
  },
  optionPillText: {
    color: colors.text,
    fontSize: 13,
  },
  optionPillTextActive: {
    color: '#2a160d',
  },
  currencyDropdownWrap: {
    marginBottom: 10,
  },
  currencyOptionsBox: {
    marginTop: 8,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  currencyOptionButton: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.accent,
    backgroundColor: colors.button,
  },
  currencyOptionButtonActive: {
    backgroundColor: colors.title,
    borderColor: colors.title,
  },
  currencyOptionText: {
    color: colors.text,
    fontSize: 14,
    fontFamily: 'serif',
  },
  currencyOptionTextActive: {
    color: '#2a160d',
  },
  removeAdvertsHeroButton: {
    marginTop: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e6c96a',
    backgroundColor: 'rgba(230, 201, 106, 0.12)',
    paddingVertical: 18,
    paddingHorizontal: 16,
    alignItems: 'center',
    shadowColor: '#e6c96a',
    shadowOpacity: 0.28,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  removeAdvertsHeroTitle: {
    color: '#f9df90',
    fontSize: 17,
    fontFamily: 'serif',
    marginBottom: 4,
  },
  removeAdvertsHeroSubtitle: {
    color: colors.text,
    fontSize: 13,
    textAlign: 'center',
  },
  crownBalanceCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.title,
    backgroundColor: 'rgba(212, 175, 55, 0.12)',
    paddingVertical: 18,
    paddingHorizontal: 16,
    alignItems: 'center',
    marginBottom: 14,
  },
  crownIcon: {
    fontSize: 30,
    marginBottom: 4,
  },
  crownBalanceValue: {
    color: colors.title,
    fontSize: 28,
    fontFamily: 'serif',
  },
  crownBalanceLabel: {
    color: colors.text,
    fontSize: 13,
  },
  shopPlan: {
    backgroundColor: colors.panel,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.accent,
    padding: 14,
    marginBottom: 12,
  },
  shopPlanTitle: {
    color: colors.title,
    fontSize: 17,
    fontFamily: 'serif',
    marginBottom: 6,
  },
  shopPlanBody: {
    color: colors.text,
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 10,
  },
  shopPlanMeta: {
    color: colors.muted,
    fontSize: 12,
    marginBottom: 8,
  },
  placeholder: {
    width: 60,
  },
  relationshipList: {
    padding: 18,
    paddingBottom: 34,
  },
  relationshipLedgerIntro: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.42)',
    backgroundColor: 'rgba(20, 10, 5, 0.55)',
    padding: 18,
    marginBottom: 16,
  },
  relationshipLedgerTitle: {
    color: colors.title,
    fontSize: 22,
    fontFamily: 'serif',
    textAlign: 'center',
    marginBottom: 6,
  },
  relationshipLedgerBody: {
    color: colors.text,
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
    marginBottom: 8,
  },
  relationshipLedgerMeta: {
    color: colors.muted,
    fontSize: 12,
    textAlign: 'center',
  },
  relationshipRow: {
    backgroundColor: '#ead9b7',
    borderRadius: 18,
    borderWidth: 2,
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
  },
  relationshipItem: {
    marginBottom: 12,
  },
  relationshipAccordion: {
    marginTop: -6,
    marginHorizontal: 12,
    paddingTop: 18,
    paddingHorizontal: 12,
    paddingBottom: 10,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    backgroundColor: 'rgba(234, 217, 183, 0.88)',
    borderWidth: 1,
    borderTopWidth: 0,
    borderColor: 'rgba(109, 65, 34, 0.32)',
  },
  relationshipName: {
    color: '#4b2c17',
    fontSize: 16,
    fontFamily: 'serif',
    flex: 1,
    marginRight: 10,
  },
  relationshipScore: {
    color: '#6d4122',
    fontSize: 13,
    textAlign: 'right',
  },
  relationshipEmpty: {
    color: colors.muted,
    fontSize: 14,
    textAlign: 'center',
    marginTop: 20,
    fontFamily: 'serif',
  },
  interactionButton: {
    borderWidth: 1,
    borderColor: 'rgba(109, 65, 34, 0.42)',
    borderRadius: 999,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(255, 249, 232, 0.5)',
    marginBottom: 10,
  },
  interactionButtonText: {
    color: '#4b2c17',
    fontSize: 13,
    textAlign: 'center',
    fontFamily: 'serif',
  },
  interactionHint: {
    color: '#6d4122',
    fontSize: 13,
    textAlign: 'center',
    fontFamily: 'serif',
  },
  memoryModalContent: {
    backgroundColor: '#ead9b7',
    paddingVertical: 16,
    paddingHorizontal: 18,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: 'rgba(109, 65, 34, 0.64)',
    width: '90%',
    maxHeight: '80%',
  },
  reportModalContent: {
    backgroundColor: '#ead9b7',
    paddingVertical: 18,
    paddingHorizontal: 18,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: 'rgba(109, 65, 34, 0.64)',
    width: '88%',
    maxWidth: 400,
  },
  reportSectionTitle: {
    color: '#6d4122',
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginTop: 8,
  },
  memorySection: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(139, 105, 20, 0.35)',
    paddingBottom: 10,
    marginBottom: 10,
  },
  memorySectionTitle: {
    color: '#6d4122',
    fontSize: 15,
    fontFamily: 'serif',
    marginBottom: 6,
  },
  memoryText: {
    color: '#4b2c17',
    fontSize: 12,
    lineHeight: 17,
    fontFamily: 'monospace',
  },
  toast: {
    position: 'absolute',
    bottom: 24,
    left: 24,
    right: 24,
    backgroundColor: colors.toastBackground,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.accent,
    padding: 12,
  },
  toastText: {
    color: colors.text,
    fontSize: 13,
    textAlign: 'center',
  },
  bannerContainer: {
    paddingBottom: 8,
    backgroundColor: colors.background,
    alignItems: 'center',
  },
  message: {
    width: '100%',
    paddingVertical: 10,
    paddingHorizontal: 8,
    marginBottom: 12,
  },
  messageText: {
    color: '#3f2716',
    fontSize: 15,
    lineHeight: 22,
    fontFamily: 'serif',
  },
  messageGame: {
    alignSelf: 'stretch',
  },
  messageUser: {
    alignSelf: 'stretch',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(109, 65, 34, 0.34)',
    backgroundColor: 'rgba(255, 249, 232, 0.36)',
  },
  storyEntryRule: {
    width: 58,
    height: 1,
    marginBottom: 8,
  },
  choiceArchiveLabel: {
    color: '#6d4122',
    fontSize: 10,
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 5,
  },
});
