export const allPeople = [ 
  'a weary seamstress',
  'a coughing cousin',
  'a neighbour carrying mended linens',
  'a handsome gentleman',
  'a flower seller',
  'a watchmaker’s apprentice',
  'a fishmonger calling out prices',
  'a stern housekeeper',
  'a footman in livery',
  'a nervous kitchen maid',
  'a flirtatious viscount',
  'a gossiping debutante',
  'a retired colonel with medals',
  'a poet with ink-stained cuffs',
  'a chaperone scanning the hedges',
  'a young heir avoiding the crowd',
  'a bookish baroness',
  'a tutor with a stack of ledgers',
  'a visiting rector',
  'a court herald',
  'a lady-in-waiting',
  'a royal page',
  'a scullery maid',
  'a cook sharpening a knife',
  'a pantry boy balancing a tray',
  'a carriage driver',
  'a horse groom',
  'a child flying a kite',
  'a postilion waiting by the horses',
  'a messenger with sealed orders',
];

export const allThings = [
  'a thimble',
  'a spool of thread',
  'a patchwork quilt',
  'a silver pocket watch',
  'a basket of oranges',
  'a bolt of muslin',
  'a jar of lavender honey',
  'a silver tray',
  'a stack of invitations',
  'a polished candelabra',
  'a lace fan',
  'a glass of champagne',
  'a satin glove',
  'a porcelain teacup',
  'a sprig of rosemary',
  'a string quartet’s program',
  'a leather-bound journal',
  'a map of the estate',
  'a chess set',
  'a velvet cushion',
  'a gilt-edged program',
  'a jeweled brooch',
  'a pot of stew',
  'a basket of fresh bread',
  'a bundle of herbs',
  'a riding crop',
  'a picnic basket',
  'a folded parasol',
  'a travel cloak',
  'a leather satchel',
];

export const peopleByContext = {
  home: [allPeople[0], allPeople[1], allPeople[2]],
  market: [allPeople[3], allPeople[4], allPeople[5], allPeople[6]],
  estate: [allPeople[7], allPeople[8], allPeople[9]],
  ballroom: [allPeople[10], allPeople[11], allPeople[12]],
  garden: [allPeople[13], allPeople[14], allPeople[15]],
  library: [allPeople[16], allPeople[17], allPeople[18]],
  royal: [allPeople[19], allPeople[20], allPeople[21]],
  kitchen: [allPeople[22], allPeople[23], allPeople[24]],
  park: [allPeople[25], allPeople[26], allPeople[27]],
  carriage: [allPeople[28], allPeople[29]],
  town: [allPeople[3], allPeople[4], allPeople[18]],
  generic: [allPeople[7], allPeople[12], allPeople[15]],
};

export const thingsByContext = {
  home: [allThings[0], allThings[1], allThings[2]],
  market: [allThings[3], allThings[4], allThings[5], allThings[6]],
  estate: [allThings[7], allThings[8], allThings[9]],
  ballroom: [allThings[10], allThings[11], allThings[12]],
  garden: [allThings[13], allThings[14], allThings[15]],
  library: [allThings[16], allThings[17], allThings[18]],
  royal: [allThings[19], allThings[20], allThings[21]],
  kitchen: [allThings[22], allThings[23], allThings[24]],
  park: [allThings[25], allThings[26], allThings[27]],
  carriage: [allThings[28], allThings[29]],
  town: [allThings[4], allThings[6], allThings[20]],
  generic: [allThings[8], allThings[11], allThings[21]],
};

