export const locationScenePools = {
  home: [
    'home_evening_vigil',
    'home_rent_threat',
    'home_storm_glass',
    'home_letter_seal',
    'home_candle_confidant',
    'home_needle_oath',
  ],
  market: [
    'market_hidden_note',
    'market_rumour_sheet',
    'market_carriage_sight',
    'market_spice_stall',
    'market_midday_rain',
    'market_muslin_bargain',
  ],
  estate: [
    'estate_gate_wait',
    'estate_corridor_glance',
    'estate_service_stairs',
    'estate_laundry_steam',
    'estate_gallery_pause',
    'estate_conservatory_path',
  ],
  ballroom: [
    'ballroom_encore',
    'ballroom_masked_corner',
    'ballroom_gossip_ring',
    'ballroom_private_balcony',
    'ballroom_champagne_spill',
    'ballroom_whispered_wager',
  ],
  garden: [
    'garden_gate_lanterns',
    'garden_hedge_listen',
    'garden_moonwalk',
    'garden_fountain_vow',
    'garden_orchard_turn',
    'garden_rose_thorns',
  ],
  library: [
    'library_lamp_whisper',
    'library_catalogue',
    'library_afterhours',
    'library_stacks_rumor',
    'library_quiet_bargain',
    'library_silent_oath',
  ],
  royal: [
    'royal_gallery_hush',
    'royal_petition',
    'royal_whisper_line',
    'royal_chapel',
    'royal_mirror',
    'royal_courtship_whisper',
  ],
  kitchen: [
    'kitchen_spill',
    'kitchen_afterhours',
    'kitchen_gossip_circle',
    'kitchen_private_pantry',
    'kitchen_orders',
    'kitchen_late_confession',
  ],
  park: [
    'park_bench_confession',
    'park_rain_shelter',
    'park_folly_mist',
    'park_procession',
    'park_lantern_challenge',
    'park_secret_letter',
  ],
  carriage: [
    'carriage_wait',
    'carriage_gate_signal',
    'carriage_drawn_shade',
    'carriage_mist_return',
    'carriage_rattle_secret',
    'carriage_after_dance',
  ],
};

export const sceneMajorRequirements = {
  market_hidden_note: 'beatrix',
  market_rumour_sheet: 'finch',
  market_carriage_sight: 'tobias',
  market_muslin_bargain: 'sabine',
  estate_corridor_glance: 'tobias',
  estate_laundry_steam: 'sabine',
  estate_gallery_pause: 'imogen',
  estate_conservatory_path: 'imogen',
  ballroom_encore: 'tobias',
  ballroom_masked_corner: 'finch',
  ballroom_gossip_ring: 'imogen',
  ballroom_private_balcony: 'tobias',
  ballroom_champagne_spill: 'sabine',
  ballroom_whispered_wager: 'tobias',
  garden_gate_lanterns: 'tobias',
  garden_hedge_listen: 'imogen',
  garden_moonwalk: 'tobias',
  garden_fountain_vow: 'sabine',
  garden_orchard_turn: 'tobias',
  garden_rose_thorns: 'imogen',
  library_lamp_whisper: 'tobias',
  library_catalogue: 'sabine',
  library_afterhours: 'tobias',
  library_stacks_rumor: 'finch',
  library_silent_oath: 'tobias',
  royal_mirror: 'imogen',
  royal_courtship_whisper: 'tobias',
  kitchen_afterhours: 'tobias',
  kitchen_private_pantry: 'tobias',
  kitchen_late_confession: 'tobias',
  park_bench_confession: 'tobias',
  park_folly_mist: 'tobias',
  park_lantern_challenge: 'imogen',
  park_secret_letter: 'finch',
  carriage_wait: 'sabine',
  carriage_gate_signal: 'tobias',
  carriage_drawn_shade: 'tobias',
  carriage_rattle_secret: 'finch',
  carriage_after_dance: 'tobias',
};
